[[intro]]
== Introduction

This document is intended to provide an overview of the RISC-V technical organizations to our members. The intended audience is both new members and existing members.

Much of this information is scattered throughout different places in the RISC-V community. We will point to other relevant documents as appropriate.

If you have suggestions about how to improve this document, find information in the document that is incomplete or broken, or simply have an unanswered question, please either post an issue in this repo or submit a “General Request” per the directions in the <<request-help>> section.

[[orgtoolsaccounts]]
=== Organizational Tools & Accounts

RISC-V information can be organized into these key tools:

* <<lftool>>
* <<portal>>
* <<wiki>>
* <<tech-calendar>>
* <<github>>
* <<google-drive>>
* <<additional-places>>

[[lftool]]
==== Linux Foundation tools (LFX)

An ever-increasing number of tools used by RISC-V are hosted out of the Linux Foundation.  Thus, members who will be actively engaged in development or leading groups at RISC-V are encouraged to request an LFX ID. 

To request one, visit the https://lfx.linuxfoundation.org/[LFX Tools] and click “Create LFX Profile”. On the Individual Dashboard, follow the “Create an account” link, complete the information, and click the blue “Create Account” button.

If you already have an LF ID, log in and https://openprofile.dev/[review your information]. In particular, visit the following pages and update information as needed.

* https://openprofile.dev/profile[Profile] to create your profile.
* https://openprofile.dev/edit/profile[Basic information] to set up your personal information.
* https://openprofile.dev/edit/connected-accounts[Connected Accounts] to specify other accounts you might have, such as GitHub and LinkedIN
* https://openprofile.dev/edit/email-management[Email Management] to handle multiple email addresses. You can set which is primary and which should receive meeting invitations.

[[portal]]
==== Portal

The RISC-V Portal (“mailing lists” or “communities”) in https://lists.riscv.org[Groups.IO].  While these lists are publicly viewable, only RISC-V members can contribute.

When you join RISC-V as an individual member or as part of your company account, you receive access to the https://lists.riscv.org/groups[Members-only mailing lists].

If your company is a RISC-V member, you can request a portal ID by sending an email to info@riscv.org from your company email, asking for an ID.

After you receive your ID, update it with your GitHub ID and your LFX ID. Follow these steps:

1. Click to https://lists.riscv.org/g/main/editprofile[edit your profile]. 
2. Log in, if needed.
3. Scroll to the bottom of the page.
4. Enter your Linux Foundation (LFX) email address (not username) in the *LFX Email* field. Note: there isn't any data validation on these fields.  So, please ensure you provide your Linux Foundation (LFX) email address (not username) in this field. See https://drive.google.com/file/d/1MtyJNDixXW8z_hrbeeMFaInLL1TViJ3-/view?usp=share_link[this video] for a quick overview.
5. Add the appropriate information in the *Github ID* field. Note: there isn't any data validation on these fields.  So, please use the Github (short) ID in this field. See https://drive.google.com/file/d/1MtyJNDixXW8z_hrbeeMFaInLL1TViJ3-/view?usp=share_link[this video] for a quick overview.
6. Submit by clicking the blue "Update Group Profile" button.

RISC-V primarily uses Groups.IO as a list server for its various groups. Join groups, review mail archives, and participate in conversations.

To locate groups, visit the RISC-V main page and follow the directions. All RISC-V groups are also directly available at the https://lists.riscv.org/g/main/subgroups[Subgroups] page.  To join any group, find the home page for the group and click the *+Join This Group* button at the bottom of the page.  To leave a group, go to the group main page, select “Subscription” in the left pane, scroll to the bottom of the page, and click the *Leave Group* button in the lower right corner.

For more information on which groups to join, please see the “Getting involved” section later in this document.

[[wiki]]
==== RISC-V Wiki

RISC-V Wiki
The https://wiki.riscv.org/[RISC-V Wiki] is also referred to as the “Technical Wiki”. 

This area can be accessed from the RISC-V Website (riscv.org) from the “Technical” menu item labeled “Technical Wiki”.  This link will bring you to the main RISC-V wiki page.

A community favorite is the Technical Overview wiki page (formerly “Important Links” or just the “URL Table”).  Bookmark this page and when searching for something, start at this page.  If you ever want to or need to contribute to the RISC-V wiki, use the <<request-help>> section and submit a “General Request” asking for wiki access.

A RISC-V “Org Chart” can be found at the “Technical Organization” item.  This interactive slide deck can be used to explore the various RISC-V groups, find Chair and Vice-chairs, and locate the community mailing list for each group. Click on boxes or use the arrows in the lower right to navigate the groups.

While the RISC-V wiki access is generally public, If you want edit capability to the RISC-V wiki, perform the following steps:


1. If you do not have an LFX (Linux Foundation) ID, see <<lftool>> and request one.
2. <<portal,Add your LFX ID email address>> to your RISC-V Portal account.
3. Request RISC-V wiki edit access by following the directions in <<request-help>>. Submit a “General Request”, asking for wiki access.

[[tech-calendar]]
==== Technical Calendar

The RISC-V Technical Calendar is available at https://tech.riscv.org/calendar/.

Chairs and vice-chairs are encouraged to keep their group meetings on this calendar. There is no invite management tooling for the groups. Meetings can be added to the calendar by simply adding tech.meetings@riscv.org to the meeting invite. Additional information about meetings, including timezone-centric links to the calendar, see the https://wiki.riscv.org/display/TECH/Calendars%2C+Meetings%2C+and+Zoom[Calendars, Meetings, and Zoom] wiki page.

[[github]]
==== GitHub

The RISC-V GitHub overview is available at https://wiki.riscv.org/display/HOME/GitHub+Repo+Map[GitHub Repo Map] wiki page.

RISC-V GitHub space contains multiple GitHub “organizations” under which the respective repositories are created.  These repositories are described in greater detail and referenced from the link on the wiki page.

All RISC-V specifications and software repositories are generally accessible.  However, contributions may be constrained to members only.  If you plan on contributing to a RISC-V GitHub repository or plan to be group Chair or Vice-Chair, the following steps should be taken:

[[google-drive]]
==== Google Drive

The Google Drive RISC-V entry point is the https://drive.google.com/drive/u/0/folders/1DemKMAD3D0Ka1MeESRoVCJipSrwiUlEs[for riscv members] folder.

While GitHub is preferred as a storage and organization tool, some activities such as spreadsheets and document collaboration are best performed with Google web-based tooling. Therefore, RISC-V has opted to anchor all of their documentation in the https://drive.google.com/drive/u/0/folders/1DemKMAD3D0Ka1MeESRoVCJipSrwiUlEs[for riscv members] folder. Generally speaking, read access to the documents should be available. 
 
When you #portal[request your RISC-V Portal access], the email address you register is automatically added to a Google group within 3 working days. The Google group provides additional access to the RISC-V documents in Google Drive. If your email is not Google, you can enable it by following the directions found in the https://support.google.com/accounts/answer/27441?hl=en#existingemail[Use an existing email address] section of the “Create a Google Account” article from Google.

To test that your membership has been set up correctly, the https://docs.google.com/document/d/1FHvKzoYb2g_PvHsIBbtHlDLhouGOtvxAptmYAt4vojw/edit[Member Authorization Test Document] was created to collect comments from RISC-V members. Directions for how to use the document and what to do if you cannot post comments are contained in the document. Similar documents also exist for the following groups
* https://docs.google.com/document/d/1krL4YB5-WE3nU3N6lQ8b8TKe5lgqsFFD5A0U5UmRdV8/[Tech Chairs Authorization Test Document]
* https://docs.google.com/document/d/1YnFXlrCRdmdz6gaRbnban8e3W7ANYRrR9tTpTsrxCfw/[Committee Chairs Authorization Test Document]
* https://docs.google.com/document/d/1_6K4OZu6sg5g8tykU1DWFx8q8aKNhYEj-gCk8rz3ZHk/[TSC Authorization Test Document]

If, for some reason your email address cannot be enabled or if you have any problems enabling it, please submit a “General Request” in the <<request-help>> section and ask for assistance with Google Drive access.

Key folders of interest:
* https://drive.google.com/drive/u/0/folders/1DemKMAD3D0Ka1MeESRoVCJipSrwiUlEs[for riscv members]: The top-level folder into which all RISC-V members content is placed.
* https://drive.google.com/drive/u/0/folders/179Vz1NtbpmFcVy8SnuSUFWAO-by2Davc[Workgroups]: Contains folders which serve as the Google drive work space for working groups.
* https://drive.google.com/drive/u/0/folders/17huuOKXafR5n4tbxZfzSnAakmgHnipoY[Policies]: Holds all RISC-V policies organized into folder for their adoption state, e.g. approved, being written, and pre-review.
* https://drive.google.com/drive/u/0/folders/1nGEt4JUDDW1dXjr78NK-5jbt8j8vuBEf[Status]: Organizes the various documents of for our specifications/work products.
* https://drive.google.com/drive/u/0/folders/1j0XmCHYwXPiZGYbfBl7WoG1AdwA2rDMR[Information]: Collects many foundational documents key to the organization.

[[additional-places]]
=== Additional places

There are additional, generally open (publicly viewable and publicly postable), mailing lists which are hosted in Google Groups and serve a variety of public purposes.  Most of these lists can be found from the https://riscv.org/technical/technical-forums/[RISC-V Technical Forums] webpage.

[[princgove]]
== Principles and governing structure

[[principles]]
=== Principles
Our Code of Conduct is published and maintained on the RISC-V website at https://riscv.org/community/community-code-of-conduct/[RISC-V Code of Conduct].  

Read more about its importance and other core ideas in the https://docs.google.com/document/d/1GTyhLDAGVxug2MKCj4gnLJGAbgw8aUa2-hhCAPFDRbU/[RISC-V Guiding Principles] document.

[[governance]]
=== Governing Group Structure and Responsibilities

The RISC-V organization is detailed in the https://docs.google.com/presentation/d/1eEVuu6lRZd9iiDnZQSZME7Q7svtTG3pGIKHPmZ79B8E/[RISC-V Technical Organization deck].

Most processes and procedures have been documented with policies documents.  All policies can be found on the https://wiki.riscv.org/display/TECH/RISC-V+Technical+Policies[RISC-V Technical Policies] wiki page.  

Commonly used policies include:

* https://docs.google.com/document/d/1_0Mnd5sXn8KcyOUI4-qvCdG7ITPY6vSAIhFc5Iy-URI/[Groups and Elections]
* https://docs.google.com/document/d/1m1zleRPI10QlczprzIWxbRa0mJyIf2AZVJl1U95776Q/[Chairs Best Practices]
* https://docs.google.com/document/d/1fhpladx9OkN8H27k7Kt0CtjgptbdDvLVRefppHwm4yI/[Ratification]
* https://docs.google.com/document/d/1uJFEpTTei_Mr78MWZ9bPRDgWj85Gh14PuX4u8p7q66o/[Acceptance Criteria]
* https://docs.google.com/document/d/1ZHA_Ds-bthEPg698g66-BvRUoy0b0uTTQnrQto17-GY/[ISA and Non-ISA]

The step-by-step directions of how to define groups and perform specification development are detailed in the https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/[RISC-V Lifecycle Guide].

[[operations]]
== Operations

[[leadership]]
=== Leadership

RISC-V CTO: 		Andrea Gallo, RISC-V
TSC Chair:		  Greg Favor, Ventana Micro Systems
TSC Vice-Chair:	Philipp Tomsich, VRULL GmbH

Full TSC membership is found in the https://docs.google.com/presentation/d/1eEVuu6lRZd9iiDnZQSZME7Q7svtTG3pGIKHPmZ79B8E/edit#slide=id.g1423212a9f5_2_128[TSC Voting Members] slide of the https://docs.google.com/presentation/d/1eEVuu6lRZd9iiDnZQSZME7Q7svtTG3pGIKHPmZ79B8E/[RISC-V Technical Organization] deck.

[[org-meetings]]
=== Organizational Meetings

The following meetings and general cadence are core to RISC-V technical organization:

* Technical Steering Committee (sometimes called “CCM” for “Committee Chairs Meeting”): generally meets 1 time per month on the first Wednesday morning of the month, U.S. time. This meeting includes all representatives from TSC-level member organizations, community elected TSC representatives (2 from the Strategic and 1 from the Community/Individual members), as well as the Chairs and Vice-chairs of HCs and ICs. However, not all CCM attendees are voting members.
* Technical Committee Chairs Coordination meeting for Committee Chairs and Vice-chairs: meets the third Wednesday morning of the month, U.S. time. The attendees include chairs of the HCs and ICs. This meeting focuses on execution only, no policy.
* Technical Chairs (and Vice-chairs) meeting (“Tech Chairs”): generally meets on the second and fourth Wednesday mornings of the month, U.S. time, and is composed of all Chairs and Vice-chairs of HCs, ICs, SIGs, and TGs.

These meetings are generally invite-only based upon membership level and group leadership.  If you need an invite, please reach out for assistance per the directions in the <<request-help>> section. 

[[getstart-chair]]
=== Getting Started as a Chair or Vice-chair of a RISC-V Group

If you have assumed a leadership role for one of the RISC-V groups, let us begin by thanking you.  The RISC-V community is a “contributor culture” that only accomplishes work when members contribute.

The first thing chairs need to understand is that RISC-V has chairs and vice-chairs only.  There is no concept of co-chairs.  Secondly, group leaders should be aware of whether their “acting” or fully confirmed (approved).  Acting chairs are used at the beginning of a group’s existence and are working to get the group and the chairs functional and officially established (approved).  More information on this process can be found in the https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/edit#heading=h.7s1dxlfz7n35[Group Lifecycle] section of the RISC-V Lifecycle Guide.

To prepare for your leadership position, please ensure to complete these steps:

. Obtain access to all tools in the <<orgtoolsaccounts>> section.
. Follow the additional guidance in the <<get-involved>> section.
. Ensure you have the appropriate Video Conferencing application setup on your workspace and that you have the host information for your group. For new groups, see the <<request-help>> section to obtain new credentials.  For existing groups, your predecessor or other chair may have this information and can share it.
. Before your first meeting, familiarize yourself with the information on https://wiki.riscv.org/display/HOME/RISC-V+Technical+Meetings[RISC-V Technical Meetings] wiki page for a primer on meeting leadership.
. Locate your group resources: RISC-V Group in the Portal (Groups.IO), Group meeting time (tech.meeting calendar), GitHub Group repo (in riscv-admin), and your Google Drive Workgroup folder. If you are an “acting” chair, these will be requested during the group creation (see “https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/edit#heading=h.rqcgvkqacfrs[Steps to Complete the Pending Milestone]” section of the RISC-V Lifecycle Guide). If you are a confirmed chair, your predecessor or other chair can help you locate these.
. If you are a confirmed chair (not “acting”), complete these few additional items:
.. Ensure that you have a meeting invite to the appropriate meeting(s) listed in the <<org-meetings>> section. You should at least have an invite to the Technical Chairs meeting.
.. Work with the RISC-V Staff to ensure that you can vote using the tool described in the <<voting>> section.  This typically involves the RISC-V Staff sending you a request to vote in a test election. They will initiate this action when ready.

[[video]]
=== Video Conferencing

RISC-V uses Zoom for group meetings. Links are provided in the calendar entries. The details for using hosting meetings with Zoom are on the “https://wiki.riscv.org/display/TECH/Calendars%2C+Meetings%2C+and+Zoom#Calendars,Meetings,andZoom-UsingZoom[Using Zoom]“ section of the "https://wiki.riscv.org/display/TECH/Calendars%2C+Meetings%2C+and+Zoom[Calendars, Meetings, and Zoom]" wiki page.

[[voting]]
=== Voting

When groups need to hold a formal vote, the https://www.opavote.com/[OpaVote] tool is used. Voters receive an email with a link to their voting credentials. Status of votes can be found on the https://wiki.riscv.org/display/TECH/RISC-V+Vote+Status[Vote Status] wiki page.

[[request-help]]
=== Requesting Help from the RISC-V Staff

Sometimes called, “The TPMs”, the RISC-V Staff has a couple of Technical Program Managers who facilitate RISC-V operations.  

To request assistance from them, create issues in the https://help.riscv.org[help.riscv.org] GitHub repository.  Forms are provided for common requests.

Unique requests can be submitted via a “General Request” issue.

If you need access to the (private) Help repository or prefer email, you may send an email to help@riscv.org[help@riscv.org].

[[specs]]
== Specifications

RISC-V is fundamentally a specification-driven organization. As such, the process by which specifications are proposed, developed, and ratified are critical to organizational success.  

All specifications (ISA or Non-ISA) have a common lifecycle and milestones. Please see the https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/[RISC-V Lifecycle Guide] for details.

Every specification being developed has two key documents: its Ratification plan document (located in one of  the https://drive.google.com/drive/u/0/folders/16bsbFBkNcKAmHBDDaauKRa80QuJglcvN[1 - Ratification Plans] folders) and its support Acceptance Criteria spreadsheet (located in one of the https://drive.google.com/drive/u/0/folders/1xWjKtdKf8Uuyyex0uZew7C1r2I0DqvOl[2 - Status Checklists folders]). These documents are created from templates, based on their document classification (ISA or Non-ISA), completed by the document owners (TG Chair and Vice-chair), and managed by the document owners and RISC-V TPMs throughout the specification development process.

During development, specification status is up-leveled from a specification’s Ratification Plan document and Acceptance Criteria into a dashboard under the https://wiki.riscv.org/display/HOME/All+Specifications+Under+Development[Specification Status] wiki page, based upon specification type and milestone.
 
Within the Task Group (TG), the specifications are developed in an open-source-like, community-driven way, involving GitHub tooling for source and issues, Asciidoctor and plugins for building the documentation, meetings for in-person coordination and larger discussions, and mailing lists for asynchronous work.  Each group forms their own norms and culture within the guidance of the RISC-V policies and structure.

To learn more about the technical aspects of developing documentation in Asciidoctor, see the https://github.com/riscv/docs-dev-guide/releases/download/main/example.pdf[Authoring and Editing RISC-V Specifications] document (or “Docs Dev Guide”).

For additional guidelines around documentation, see the (still draft version) https://docs.google.com/document/d/1zRUSx8Cx3MhQqKCGBlhfLxhdwNMW8Ajwsv12M69y3kY/[RISC-V Technical Documentation Policy] document.

[[software]]
== Software

The RISC-V software initiatives are anchored in the Software Horizontal Committee (HC):

* https://lists.riscv.org/g/software[Groups.IO group] (members only mailing list): https://lists.riscv.org/g/software 
* Software ecosystem components and status: https://wiki.riscv.org/display/HOME/RISC-V+Software+Ecosystem[Software Ecosystem] wiki page
* External mailing list: https://groups.google.com/u/1/a/groups.riscv.org/g/sw-dev[sw-dev]
* RISC-V member patch review lists (new): 
** https://groups.google.com/a/riscv.org/g/dev-gnu-patches[dev-gnu-patches]
** https://groups.google.com/a/riscv.org/g/dev-kernel-patches[dev-kernel-patches]
** https://groups.google.com/a/riscv.org/g/dev-libs-patches[dev-libs-patches]
** https://groups.google.com/a/riscv.org/g/dev-llvm-patches[dev-llvm-patches]
** https://groups.google.com/a/riscv.org/g/dev-simulator-patches[dev-simulator-patches]

Almost every ISA extension impacts some piece of the software ecosystem.  Details about the https://docs.google.com/presentation/d/1nQ5uFb39KA6gvUi5SReWfIQSiRN7hp6z7ZPfctE4mKk/edit#slide=id.g104ba5e7139_0_569[RISC-V Software Development Lifecycle] (and https://docs.google.com/presentation/d/1nQ5uFb39KA6gvUi5SReWfIQSiRN7hp6z7ZPfctE4mKk/edit#slide=id.g104d04b92b1_1_1[Milestones]) exist in the https://docs.google.com/presentation/d/1nQ5uFb39KA6gvUi5SReWfIQSiRN7hp6z7ZPfctE4mKk/edit?usp=sharing[Specification Lifecycle and Milestone Definitions] slides.

[[get-involved]]
== Getting involved
To contribute to a specification or a technical area, find the most appropriate group in Groups.IO, join it, follow the discussions on the mailing list, attend the meetings, and volunteer to help.

To engage in the development of an active specification, visit the https://wiki.riscv.org/display/HOME/All+Specifications+Under+Development[Specification Status] wiki page, locate the Task Group or Committee that owns the specification and join the group via the links provided.

If you are a member of the RISC-V Technical community, you should join the following groups:

* “https://lists.riscv.org/g/allmem[All Members]” (allmem) group to receive community-wide notifications.
* “https://lists.riscv.org/g/tech-announce[Tech Announce]” (tech-announce) group to stay in touch with all things technical, including leadership “Call for Candidate” notices, specification reviews, and groups formation announcements.

Additional groups of interest are the ISA and Horizontal Committees (ICs and HCs).  These groups are:

* "https://lists.riscv.org/g/tech-unprivileged[Unprivileged ISA Committee]” (tech-unprivileged) group for discussions about user-mode extensions.
* "https://lists.riscv.org/g/tech-privileged[Privileged ISA Committee]" (tech-privileged) group for discussions about all privilege mode extensions.
* “https://lists.riscv.org/g/apps-tools-software[Applications & Tools Horizontal Committee]” (apps-tools-software) group for discussions about tools, toolchains, compilers, and applications.
* “https://lists.riscv.org/g/privileged-software[Privileged Software Horizontal Committee]” (privileged-software) group for discussions about platform enablement software such as firmware, kernels, hypervisors, etc.
* “https://lists.riscv.org/g/security[Security Horizontal Committee]” (security) group for discussions on all security topics
* “https://lists.riscv.org/g/isa-infra[ISA Infrastructure Horizontal Committee]” (isa-infra) group for discussions around non-extension discussions for the ISA such as Architectural Compatibility Testing (ACT), SAIL model development, documentation guidance, and Continuous Integration testing of the development tools.
* “https://lists.riscv.org/g/soc-infra[SOC Infrastructure Horizontal Committee]” (soc-infra) group for discussions about the components which straddle the hardware/software boundary such as RAS, Debug, Trace, and IOMMU.
* “https://lists.riscv.org/g/tech-sectors[Technology Horizontal Committee]” (tech-sectors) group for market segment discussions like Datacenter, HPC, and Embedded

To find a list of all existing groups, see the RISC-V Portal page for https://lists.riscv.org/g/main/subgroups[Sub-groups].

To find the list of all existing and proposed groups, review the “Technical Org Chart” link on the main https://wiki.riscv.org/[RISC-V wiki page].

To propose a new group, see https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/edit#heading=h.7s1dxlfz7n35[2. Group Lifecycle] section of the https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/[RISC-V Lifecycle Guide].  If needed, see the <<request-help>> section for guidance on how to get more assistance. 

To propose a new specification or topic, see https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/edit#heading=h.vp6ntzpqto3j[3. Specification Lifecycle] section of the https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/[RISC-V Lifecycle Guide].  See the <<request-help>> section for guidance on how to request more assistance.

To find an answer to a question, try one of these methods.

. Review a list of common questions in the https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/edit#heading=h.gmhptxzcxepg[Frequently Asked Questions (FAQs)] section of the RISC-V Lifecycle Guide.
. For questions about the ISA or compilers and software, post to the external mailing lists: https://groups.google.com/u/1/a/groups.riscv.org/g/isa-dev[isa-dev] and https://groups.google.com/u/1/a/groups.riscv.org/g/sw-dev[sw-dev].
. Check out the working groups (see <<orgtoolsaccounts>>) to see if the topic is already discussed. Join and ask!
. Join the https://join.slack.com/t/risc-v-international/signup[RISC-V Slack workspace] and post to either the #random or #tech-general channels.
. If all else fails, see the <<request-help>> section for guidance on how to get more assistance.

[[nomenclature]]
== Nomenclature

Understanding the following terms and definitions will help navigating the RISC-V development community.

The following sections define some of the most common terms.  Additional terms can be found in the https://docs.google.com/document/d/1Au3veNdNJQKPq-oiQRKTzdgmM72FDaqZOKeH7sOnG04/edit#heading=h.t356lc88wwo9[Appendix] of the RISC-V Lifecycle Guide.

You can find additional terms at the https://github.com/riscv/riscv-glossary/blob/main/src/glossary.adoc[RISC-V glossary].

[[extensions]]
=== Extensions

Extensions are a group of instructions and state (registers, CSRs) and the behaviors for those instructions and state. The extension is defined by a specification (or chapter in a specification) and a formal model in SAIL. Extensions are governed and approved by the TSC and ratified by the Board of Directors and extensions along with their corresponding task groups are governed by their committee and their charter is governed and approved by TSC.

An extension has a name. The name is governed, allocated and approved by the Unprivileged IC and appears in a chapter in the Unprivileged specification. Extension names may be individual alphabetic letters or may begin with a [ZSM]<string> for RISC-V extensions and X<string> for custom vendor specific non-standard extensions.

[[rat-packages]]
=== Ratification Packages

Extensions are grouped together into a set which is documented in a single specification and ratified at the same time. This group is the Ratification Package or “Rat Pack” for short.

[[profile-ext]]
=== Profiles

Profiles are a collection of extensions which is more broad than the Ratification Package. You can find more information in the https://github.com/riscv/riscv-profiles[source repository] for the RISC-V Profiles.

[[platform]]
=== Platforms

Platforms define a set of requirements (including Profiles and other hardware and software standards) for interoperability between software and hardware and among all software distributions. Find more information in the https://github.com/riscv-admin/server-platform[source repository] for the RISC-V Platform specification.


